included:
  - bikecheck
  - bikecheckTests

excluded:
  - Pods
  - .build
  - build
  - Carthage
  - DerivedData

disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - unused_import

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - x
    - y

type_name:
  min_length: 3
  max_length: 50

reporter: "xcode"
