name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Xcode
        run: xcode-select -p

      - name: Install dependencies
        run: |
          gem install xcpretty
          gem install xcpretty-json-formatter
      
      - name: Run tests
        run: |
          xcodebuild test \
            -project bikecheck.xcodeproj \
            -scheme bikecheck \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' \
            | xcpretty --report junit --output test-results/junit.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results
          
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # Always run even if the previous step fails
        with:
          report_paths: 'test-results/junit.xml'
          fail_on_failure: true
          require_tests: true
          include_passed: true
          detailed_summary: true
          check_name: 'iOS Test Results'