name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Xcode
        run: xcode-select -p
      
      - name: Run Unit tests
        run: |
          xcodebuild test \
            -project bikecheck.xcodeproj \
            -scheme bikecheck \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' \
            -only-testing:bikecheckTests
      
      - name: Run UI tests
        run: |
          xcodebuild test \
            -project bikecheck.xcodeproj \
            -scheme bikecheck \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' \
            -only-testing:bikecheckUITests
